# dev_password.cmake -- the dev channel's shared password, into the dev exe at
# build time only (#26, docs/SPEC.md "Dev channel"). Run by the ffb_coop_dev
# build (CMakeLists.txt) as `cmake -DOUT=<header> -P cmake/dev_password.cmake`.
#
# The password is never in the repo. It is read, in this order, from:
#   1. the environment variable FFB_DEV_PASSWORD;
#   2. the file named by the environment variable FFB_DEV_PASSWORD_FILE;
#   3. ~/.config/coopmods/ffb-dev-password ($HOME, then %USERPROFILE%), where
#      the lead keeps it on the WSL side.
# Leading and trailing whitespace (the file's newline) is dropped. With none of
# them, or an empty or multi-line password, the build stops here: a dev exe
# with no credential is never built.
#
# OUT is a header in the build tree, rewritten only when the password changed
# (so an unchanged one rebuilds nothing). It holds the password as \x escapes;
# nothing here prints it.
cmake_minimum_required(VERSION 3.21)

if(NOT OUT)
    message(FATAL_ERROR "dev_password.cmake: run with -DOUT=<header to write>")
endif()

set(_pw "")
set(_from "")
if(NOT "$ENV{FFB_DEV_PASSWORD}" STREQUAL "")
    set(_pw "$ENV{FFB_DEV_PASSWORD}")
    set(_from "the environment variable FFB_DEV_PASSWORD")
else()
    set(_candidates "")
    if(NOT "$ENV{FFB_DEV_PASSWORD_FILE}" STREQUAL "")
        list(APPEND _candidates "$ENV{FFB_DEV_PASSWORD_FILE}")
        if(NOT EXISTS "$ENV{FFB_DEV_PASSWORD_FILE}")
            message(FATAL_ERROR "FFB Co-op - dev.exe: FFB_DEV_PASSWORD_FILE names $ENV{FFB_DEV_PASSWORD_FILE}, "
                                "which does not exist")
        endif()
    endif()
    foreach(_home "$ENV{HOME}" "$ENV{USERPROFILE}")
        if(NOT _home STREQUAL "")
            list(APPEND _candidates "${_home}/.config/coopmods/ffb-dev-password")
        endif()
    endforeach()
    foreach(_file IN LISTS _candidates)
        if(EXISTS "${_file}")
            file(READ "${_file}" _pw)
            set(_from "${_file}")
            break()
        endif()
    endforeach()
endif()

string(STRIP "${_pw}" _pw)
if(_pw STREQUAL "")
    if(_from STREQUAL "")
        message(FATAL_ERROR
            "FFB Co-op - dev.exe needs the dev channel's shared password, and none was found.\n"
            "Set FFB_DEV_PASSWORD, or FFB_DEV_PASSWORD_FILE to a file holding it, or put it in "
            "~/.config/coopmods/ffb-dev-password. To build only FFB Co-op.exe, configure with -DFFB_BUILD_DEV=OFF.")
    else()
        message(FATAL_ERROR "FFB Co-op - dev.exe: the dev password from ${_from} is empty")
    endif()
endif()
if(_pw MATCHES "[\r\n]")
    message(FATAL_ERROR "FFB Co-op - dev.exe: the dev password from ${_from} spans more than one line")
endif()

string(HEX "${_pw}" _hex)
string(REGEX REPLACE "(..)" "\\\\x\\1" _escaped "${_hex}")
set(_content "// Generated by cmake/dev_password.cmake for FFB Co-op - dev.exe. Never commit it.\n"
             "#pragma once\n"
             "#define FFB_DEV_PASSWORD \"${_escaped}\"\n")
string(CONCAT _content ${_content})

set(_old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" _old)
endif()
if(NOT _old STREQUAL _content)
    file(WRITE "${OUT}" "${_content}")
endif()
